# Generated by Django 5.0.6 on 2024-06-01 15:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=128, verbose_name='event type')),
                ('event_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'column event',
            },
        ),
        migrations.CreateModel(
            name='TableEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=128, verbose_name='event type')),
                ('event_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'table event',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(editable=False, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('schema', models.ForeignKey(help_text='Select a schema', on_delete=django.db.models.deletion.CASCADE, to='schemas.schema', verbose_name='schema')),
            ],
            options={
                'verbose_name': 'table',
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(editable=False, null=True, verbose_name='deleted at')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('type', models.CharField(max_length=128, verbose_name='type')),
                ('details', models.JSONField(blank=True, verbose_name='details')),
                ('table', models.ForeignKey(help_text='Select a table', on_delete=django.db.models.deletion.CASCADE, to='tables.table', verbose_name='table')),
            ],
            options={
                'verbose_name': 'column',
            },
        ),
    ]
