# Generated by Django 5.0.6 on 2024-06-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='table',
        ),
        migrations.DeleteModel(
            name='ColumnEvent',
        ),
        migrations.DeleteModel(
            name='Column',
        ),
    ]
