# Generated by Django 5.0.6 on 2024-06-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_remove_column_table_delete_columnevent_delete_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='schema_name',
            field=models.CharField(default=2, max_length=128, verbose_name='schema name'),
            preserve_default=False,
        ),
    ]
