# Generated by Django 5.0.6 on 2024-06-01 15:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=128, verbose_name='event type')),
                ('event_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'schema event',
            },
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(editable=False, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('storage', models.ForeignKey(help_text='Select a storage', on_delete=django.db.models.deletion.CASCADE, to='storages.storage', verbose_name='storage')),
            ],
            options={
                'verbose_name': 'schema',
            },
        ),
    ]
