# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpc_client.storages_pb2 as storages__pb2


class DataSourceManageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSchemas = channel.unary_unary(
                '/schemas.DataSourceManageService/GetSchemas',
                request_serializer=storages__pb2.SchemaRequest.SerializeToString,
                response_deserializer=storages__pb2.SchemaResponse.FromString,
                )
        self.GetTables = channel.unary_unary(
                '/schemas.DataSourceManageService/GetTables',
                request_serializer=storages__pb2.TableRequest.SerializeToString,
                response_deserializer=storages__pb2.TableResponse.FromString,
                )
        self.GetColumns = channel.unary_unary(
                '/schemas.DataSourceManageService/GetColumns',
                request_serializer=storages__pb2.ColumnRequest.SerializeToString,
                response_deserializer=storages__pb2.ColumnResponse.FromString,
                )
        self.GetViews = channel.unary_unary(
                '/schemas.DataSourceManageService/GetViews',
                request_serializer=storages__pb2.ViewRequest.SerializeToString,
                response_deserializer=storages__pb2.ViewResponse.FromString,
                )
        self.DoMigration = channel.unary_unary(
                '/schemas.DataSourceManageService/DoMigration',
                request_serializer=storages__pb2.MigrationRequest.SerializeToString,
                response_deserializer=storages__pb2.MigrationResponse.FromString,
                )


class DataSourceManageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSchemas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTables(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetColumns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetViews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DoMigration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataSourceManageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSchemas': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchemas,
                    request_deserializer=storages__pb2.SchemaRequest.FromString,
                    response_serializer=storages__pb2.SchemaResponse.SerializeToString,
            ),
            'GetTables': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTables,
                    request_deserializer=storages__pb2.TableRequest.FromString,
                    response_serializer=storages__pb2.TableResponse.SerializeToString,
            ),
            'GetColumns': grpc.unary_unary_rpc_method_handler(
                    servicer.GetColumns,
                    request_deserializer=storages__pb2.ColumnRequest.FromString,
                    response_serializer=storages__pb2.ColumnResponse.SerializeToString,
            ),
            'GetViews': grpc.unary_unary_rpc_method_handler(
                    servicer.GetViews,
                    request_deserializer=storages__pb2.ViewRequest.FromString,
                    response_serializer=storages__pb2.ViewResponse.SerializeToString,
            ),
            'DoMigration': grpc.unary_unary_rpc_method_handler(
                    servicer.DoMigration,
                    request_deserializer=storages__pb2.MigrationRequest.FromString,
                    response_serializer=storages__pb2.MigrationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'schemas.DataSourceManageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataSourceManageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSchemas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/schemas.DataSourceManageService/GetSchemas',
            storages__pb2.SchemaRequest.SerializeToString,
            storages__pb2.SchemaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/schemas.DataSourceManageService/GetTables',
            storages__pb2.TableRequest.SerializeToString,
            storages__pb2.TableResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetColumns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/schemas.DataSourceManageService/GetColumns',
            storages__pb2.ColumnRequest.SerializeToString,
            storages__pb2.ColumnResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetViews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/schemas.DataSourceManageService/GetViews',
            storages__pb2.ViewRequest.SerializeToString,
            storages__pb2.ViewResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DoMigration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/schemas.DataSourceManageService/DoMigration',
            storages__pb2.MigrationRequest.SerializeToString,
            storages__pb2.MigrationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
