# Generated by Django 5.0.6 on 2024-06-01 15:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(editable=False, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('vendor', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL')], verbose_name='vendor')),
                ('username', models.CharField(max_length=128, verbose_name='username')),
                ('password', models.CharField(verbose_name='password')),
                ('host', models.GenericIPAddressField(help_text='Enter host.', verbose_name='host')),
                ('port', models.PositiveIntegerField(verbose_name='port')),
                ('owner_id', models.UUIDField(default=uuid.uuid4, verbose_name='owner ID')),
                ('group_id', models.UUIDField(default=uuid.uuid4, verbose_name='group ID')),
            ],
            options={
                'verbose_name': 'Storage',
            },
        ),
        migrations.CreateModel(
            name='StorageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=128, verbose_name='event type')),
                ('event_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'storage event',
            },
        ),
    ]
