# Generated by Django 5.0.6 on 2024-06-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='is_connect',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='is connect'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='vendor',
            field=models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql+mysqldb', 'MySQL')], verbose_name='vendor'),
        ),
    ]
