# Generated by Django 5.0.6 on 2024-06-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0002_storage_is_connect_alter_storage_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='password'),
        ),
    ]
